-- MySQL Script generated by MySQL Workbench
-- Sun Jul 21 15:11:17 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gojudge
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gojudge
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gojudge` DEFAULT CHARACTER SET utf8 ;
USE `gojudge` ;

-- -----------------------------------------------------
-- Table `gojudge`.`problems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gojudge`.`problems` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `shortname` VARCHAR(45) NULL,
  `timelimit` INT NULL,
  `memlimit` INT NULL,
  `text` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gojudge`.`submissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gojudge`.`submissions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL,
  `time` DATETIME NULL,
  `problem_id` INT NULL,
  `verdict` VARCHAR(45) NULL,
  `passed_tests` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gojudge`.`tests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gojudge`.`tests` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `problem_id` INT NULL,
  `order` INT NULL,
  `is_sample` INT NULL,
  `input` BLOB NULL,
  `output` BLOB NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gojudge`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gojudge`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `fullname` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `access` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
